function onChange(input){
  document.querySelector(".input").value = input;
  console.log("Input changed", input);
}

function onKeyPress(button){
  console.log("Button pressed", button);
}


const animationDuration = 500 // ms

let height = 5; // Number of Guesses
let width = 8; // Length of Word

let row = 0; // Current Guess Attempt
let col = 0; // Current Letter

let words = ['ABANDON', 'ABILITY', 'ABORTION', 'ABROAD', 'ABSENCE', 'ABSOLUTE', 'ABSOLUTELY', 'ABSORB', 'ACADEMIC', 'ACCEPT', 'ACCESS', 'ACCIDENT', 'ACCOMPANY', 'ACCOMPLISH', 'ACCORDING', 'ACCOUNT', 'ACCURATE', 'ACCUSE', 'ACHIEVE', 'ACHIEVEMENT', 'ACKNOWLEDGE', 'ACQUIRE', 'ACROSS', 'ACTION', 'ACTIVE', 'ACTIVIST', 'ACTIVITY', 'ACTRESS', 'ACTUAL', 'ACTUALLY', 'ADDITION', 'ADDITIONAL', 'ADDRESS', 'ADEQUATE', 'ADJUST', 'ADJUSTMENT', 'ADMINISTRATION', 'ADMINISTRATOR', 'ADMIRE', 'ADMISSION', 'ADOLESCENT', 'ADVANCE', 'ADVANCED', 'ADVANTAGE', 'ADVENTURE', 'ADVERTISING', 'ADVICE', 'ADVISE', 'ADVISER', 'ADVOCATE', 'AFFAIR', 'AFFECT', 'AFFORD', 'AFRAID', 'AFRICAN', 'AFRICAN-AMERICAN', 'AFTERNOON', 'AGAINST', 'AGENCY', 'AGENDA', 'AGGRESSIVE', 'AGREEMENT', 'AGRICULTURAL', 'AIRCRAFT', 'AIRLINE', 'AIRPORT', 'ALCOHOL', 'ALLIANCE', 'ALMOST', 'ALREADY', 'ALTERNATIVE', 'ALTHOUGH', 'ALWAYS', 'AMAZING', 'AMERICAN', 'AMOUNT', 'ANALYSIS', 'ANALYST', 'ANALYZE', 'ANCIENT', 'ANIMAL', 'ANNIVERSARY', 'ANNOUNCE', 'ANNUAL', 'ANOTHER', 'ANSWER', 'ANTICIPATE', 'ANXIETY', 'ANYBODY', 'ANYMORE', 'ANYONE', 'ANYTHING', 'ANYWAY', 'ANYWHERE', 'APARTMENT', 'APPARENT', 'APPARENTLY', 'APPEAL', 'APPEAR', 'APPEARANCE', 'APPLICATION', 'APPOINT', 'APPOINTMENT', 'APPRECIATE', 'APPROACH', 'APPROPRIATE', 'APPROVAL', 'APPROVE', 'APPROXIMATELY', 'ARCHITECT', 'ARGUMENT', 'AROUND', 'ARRANGE', 'ARRANGEMENT', 'ARREST', 'ARRIVAL', 'ARRIVE', 'ARTICLE', 'ARTIST', 'ARTISTIC', 'ASLEEP', 'ASPECT', 'ASSAULT', 'ASSERT', 'ASSESS', 'ASSESSMENT', 'ASSIGN', 'ASSIGNMENT', 'ASSIST', 'ASSISTANCE', 'ASSISTANT', 'ASSOCIATE', 'ASSOCIATION', 'ASSUME', 'ASSUMPTION', 'ASSURE', 'ATHLETE', 'ATHLETIC', 'ATMOSPHERE', 'ATTACH', 'ATTACK', 'ATTEMPT', 'ATTEND', 'ATTENTION', 'ATTITUDE', 'ATTORNEY', 'ATTRACT', 'ATTRACTIVE', 'ATTRIBUTE', 'AUDIENCE', 'AUTHOR', 'AUTHORITY', 'AVAILABLE', 'AVERAGE', 'AWARENESS', 'BACKGROUND', 'BALANCE', 'BARELY', 'BARREL', 'BARRIER', 'BASEBALL', 'BASICALLY', 'BASKET', 'BASKETBALL', 'BATHROOM', 'BATTERY', 'BATTLE', 'BEAUTIFUL', 'BEAUTY', 'BECAUSE', 'BECOME', 'BEDROOM', 'BEFORE', 'BEGINNING', 'BEHAVIOR', 'BEHIND', 'BELIEF', 'BELIEVE', 'BELONG', 'BENEATH', 'BENEFIT', 'BESIDE', 'BESIDES', 'BETTER', 'BETWEEN', 'BEYOND', 'BILLION', 'BIOLOGICAL', 'BIRTHDAY', 'BLANKET', 'BOMBING', 'BORDER', 'BORROW', 'BOTHER', 'BOTTLE', 'BOTTOM', 'BOUNDARY', 'BOYFRIEND', 'BRANCH', 'BREAKFAST', 'BREAST', 'BREATH', 'BREATHE', 'BRIDGE', 'BRIEFLY', 'BRIGHT', 'BRILLIANT', 'BRITISH', 'BROKEN', 'BROTHER', 'BUDGET', 'BUILDING', 'BULLET', 'BURDEN', 'BUSINESS', 'BUTTER', 'BUTTON', 'CABINET', 'CALCULATE', 'CAMERA', 'CAMPAIGN', 'CAMPUS', 'CANADIAN', 'CANCER', 'CANDIDATE', 'CAPABILITY', 'CAPABLE', 'CAPACITY', 'CAPITAL', 'CAPTAIN', 'CAPTURE', 'CARBON', 'CAREER', 'CAREFUL', 'CAREFULLY', 'CARRIER', 'CATEGORY', 'CATHOLIC', 'CEILING', 'CELEBRATE', 'CELEBRATION', 'CELEBRITY', 'CENTER', 'CENTRAL', 'CENTURY', 'CEREMONY', 'CERTAIN', 'CERTAINLY', 'CHAIRMAN', 'CHALLENGE', 'CHAMBER', 'CHAMPION', 'CHAMPIONSHIP', 'CHANCE', 'CHANGE', 'CHANGING', 'CHANNEL', 'CHAPTER', 'CHARACTER', 'CHARACTERISTIC', 'CHARACTERIZE', 'CHARGE', 'CHARITY', 'CHEESE', 'CHEMICAL', 'CHICKEN', 'CHILDHOOD', 'CHINESE', 'CHOCOLATE', 'CHOICE', 'CHOLESTEROL', 'CHOOSE', 'CHRISTIAN', 'CHRISTMAS', 'CHURCH', 'CIGARETTE', 'CIRCLE', 'CIRCUMSTANCE', 'CITIZEN', 'CIVILIAN', 'CLASSIC', 'CLASSROOM', 'CLEARLY', 'CLIENT', 'CLIMATE', 'CLINIC', 'CLINICAL', 'CLOSELY', 'CLOSER', 'CLOTHES', 'CLOTHING', 'CLUSTER', 'COALITION', 'COFFEE', 'COGNITIVE', 'COLLAPSE', 'COLLEAGUE', 'COLLECT', 'COLLECTION', 'COLLECTIVE', 'COLLEGE', 'COLONIAL', 'COLUMN', 'COMBINATION', 'COMBINE', 'COMEDY', 'COMFORT', 'COMFORTABLE', 'COMMAND', 'COMMANDER', 'COMMENT', 'COMMERCIAL', 'COMMISSION', 'COMMIT', 'COMMITMENT', 'COMMITTEE', 'COMMON', 'COMMUNICATE', 'COMMUNICATION', 'COMMUNITY', 'COMPANY', 'COMPARE', 'COMPARISON', 'COMPETE', 'COMPETITION', 'COMPETITIVE', 'COMPETITOR', 'COMPLAIN', 'COMPLAINT', 'COMPLETE', 'COMPLETELY', 'COMPLEX', 'COMPLICATED', 'COMPONENT', 'COMPOSE', 'COMPOSITION', 'COMPREHENSIVE', 'COMPUTER', 'CONCENTRATE', 'CONCENTRATION', 'CONCEPT', 'CONCERN', 'CONCERNED', 'CONCERT', 'CONCLUDE', 'CONCLUSION', 'CONCRETE', 'CONDITION', 'CONDUCT', 'CONFERENCE', 'CONFIDENCE', 'CONFIDENT', 'CONFIRM', 'CONFLICT', 'CONFRONT', 'CONFUSION', 'CONGRESS', 'CONGRESSIONAL', 'CONNECT', 'CONNECTION', 'CONSCIOUSNESS', 'CONSENSUS', 'CONSEQUENCE', 'CONSERVATIVE', 'CONSIDER', 'CONSIDERABLE', 'CONSIDERATION', 'CONSIST', 'CONSISTENT', 'CONSTANT', 'CONSTANTLY', 'CONSTITUTE', 'CONSTITUTIONAL', 'CONSTRUCT', 'CONSTRUCTION', 'CONSULTANT', 'CONSUME', 'CONSUMER', 'CONSUMPTION', 'CONTACT', 'CONTAIN', 'CONTAINER', 'CONTEMPORARY', 'CONTENT', 'CONTEST', 'CONTEXT', 'CONTINUE', 'CONTINUED', 'CONTRACT', 'CONTRAST', 'CONTRIBUTE', 'CONTRIBUTION', 'CONTROL', 'CONTROVERSIAL', 'CONTROVERSY', 'CONVENTION', 'CONVENTIONAL', 'CONVERSATION', 'CONVERT', 'CONVICTION', 'CONVINCE', 'COOKIE', 'COOKING', 'COOPERATION', 'CORNER', 'CORPORATE', 'CORPORATION', 'CORRECT', 'CORRESPONDENT', 'COTTON', 'COUNCIL', 'COUNSELOR', 'COUNTER', 'COUNTRY', 'COUNTY', 'COUPLE', 'COURAGE', 'COURSE', 'COUSIN', 'COVERAGE', 'CREATE', 'CREATION', 'CREATIVE', 'CREATURE', 'CREDIT', 'CRIMINAL', 'CRISIS', 'CRITERIA', 'CRITIC', 'CRITICAL', 'CRITICISM', 'CRITICIZE', 'CRUCIAL', 'CULTURAL', 'CULTURE', 'CURIOUS', 'CURRENT', 'CURRENTLY', 'CURRICULUM', 'CUSTOM', 'CUSTOMER', 'DAMAGE', 'DANGER', 'DANGEROUS', 'DARKNESS', 'DAUGHTER', 'DEALER', 'DEBATE', 'DECADE', 'DECIDE', 'DECISION', 'DECLARE', 'DECLINE', 'DECREASE', 'DEEPLY', 'DEFEAT', 'DEFEND', 'DEFENDANT', 'DEFENSE', 'DEFENSIVE', 'DEFICIT', 'DEFINE', 'DEFINITELY', 'DEFINITION', 'DEGREE', 'DELIVER', 'DELIVERY', 'DEMAND', 'DEMOCRACY', 'DEMOCRAT', 'DEMOCRATIC', 'DEMONSTRATE', 'DEMONSTRATION', 'DEPARTMENT', 'DEPEND', 'DEPENDENT', 'DEPENDING', 'DEPICT', 'DEPRESSION', 'DEPUTY', 'DERIVE', 'DESCRIBE', 'DESCRIPTION', 'DESERT', 'DESERVE', 'DESIGN', 'DESIGNER', 'DESIRE', 'DESPERATE', 'DESPITE', 'DESTROY', 'DESTRUCTION', 'DETAIL', 'DETAILED', 'DETECT', 'DETERMINE', 'DEVELOP', 'DEVELOPING', 'DEVELOPMENT', 'DEVICE', 'DEVOTE', 'DIALOGUE', 'DIFFER', 'DIFFERENCE', 'DIFFERENT', 'DIFFERENTLY', 'DIFFICULT', 'DIFFICULTY', 'DIGITAL', 'DIMENSION', 'DINING', 'DINNER', 'DIRECT', 'DIRECTION', 'DIRECTLY', 'DIRECTOR', 'DISABILITY', 'DISAGREE', 'DISAPPEAR', 'DISASTER', 'DISCIPLINE', 'DISCOURSE', 'DISCOVER', 'DISCOVERY', 'DISCRIMINATION', 'DISCUSS', 'DISCUSSION', 'DISEASE', 'DISMISS', 'DISORDER', 'DISPLAY', 'DISPUTE', 'DISTANCE', 'DISTANT', 'DISTINCT', 'DISTINCTION', 'DISTINGUISH', 'DISTRIBUTE', 'DISTRIBUTION', 'DISTRICT', 'DIVERSE', 'DIVERSITY', 'DIVIDE', 'DIVISION', 'DIVORCE', 'DOCTOR', 'DOCUMENT', 'DOMESTIC', 'DOMINANT', 'DOMINATE', 'DOUBLE', 'DOWNTOWN', 'DRAMATIC', 'DRAMATICALLY', 'DRAWING', 'DRIVER', 'DURING', 'EARNINGS', 'EASILY', 'EASTERN', 'ECONOMIC', 'ECONOMICS', 'ECONOMIST', 'ECONOMY', 'EDITION', 'EDITOR', 'EDUCATE', 'EDUCATION', 'EDUCATIONAL', 'EDUCATOR', 'EFFECT', 'EFFECTIVE', 'EFFECTIVELY', 'EFFICIENCY', 'EFFICIENT', 'EFFORT', 'EITHER', 'ELDERLY', 'ELECTION', 'ELECTRIC', 'ELECTRICITY', 'ELECTRONIC', 'ELEMENT', 'ELEMENTARY', 'ELIMINATE', 'ELSEWHERE', 'E-MAIL', 'EMBRACE', 'EMERGE', 'EMERGENCY', 'EMISSION', 'EMOTION', 'EMOTIONAL', 'EMPHASIS', 'EMPHASIZE', 'EMPLOY', 'EMPLOYEE', 'EMPLOYER', 'EMPLOYMENT', 'ENABLE', 'ENCOUNTER', 'ENCOURAGE', 'ENERGY', 'ENFORCEMENT', 'ENGAGE', 'ENGINE', 'ENGINEER', 'ENGINEERING', 'ENGLISH', 'ENHANCE', 'ENORMOUS', 'ENOUGH', 'ENSURE', 'ENTERPRISE', 'ENTERTAINMENT', 'ENTIRE', 'ENTIRELY', 'ENTRANCE', 'ENVIRONMENT', 'ENVIRONMENTAL', 'EPISODE', 'EQUALLY', 'EQUIPMENT', 'ESCAPE', 'ESPECIALLY', 'ESSENTIAL', 'ESSENTIALLY', 'ESTABLISH', 'ESTABLISHMENT', 'ESTATE', 'ESTIMATE', 'ETHICS', 'ETHNIC', 'EUROPEAN', 'EVALUATE', 'EVALUATION', 'EVENING', 'EVENTUALLY', 'EVERYBODY', 'EVERYDAY', 'EVERYONE', 'EVERYTHING', 'EVERYWHERE', 'EVIDENCE', 'EVOLUTION', 'EVOLVE', 'EXACTLY', 'EXAMINATION', 'EXAMINE', 'EXAMPLE', 'EXCEED', 'EXCELLENT', 'EXCEPT', 'EXCEPTION', 'EXCHANGE', 'EXCITING', 'EXECUTIVE', 'EXERCISE', 'EXHIBIT', 'EXHIBITION', 'EXISTENCE', 'EXISTING', 'EXPAND', 'EXPANSION', 'EXPECT', 'EXPECTATION', 'EXPENSE', 'EXPENSIVE', 'EXPERIENCE', 'EXPERIMENT', 'EXPERT', 'EXPLAIN', 'EXPLANATION', 'EXPLODE', 'EXPLORE', 'EXPLOSION', 'EXPOSE', 'EXPOSURE', 'EXPRESS', 'EXPRESSION', 'EXTEND', 'EXTENSION', 'EXTENSIVE', 'EXTENT', 'EXTERNAL', 'EXTRAORDINARY', 'EXTREME', 'EXTREMELY', 'FABRIC', 'FACILITY', 'FACTOR', 'FACTORY', 'FACULTY', 'FAILURE', 'FAIRLY', 'FAMILIAR', 'FAMILY', 'FAMOUS', 'FANTASY', 'FARMER', 'FASHION', 'FATHER', 'FAVORITE', 'FEATURE', 'FEDERAL', 'FEELING', 'FELLOW', 'FEMALE', 'FICTION', 'FIFTEEN', 'FIGHTER', 'FIGHTING', 'FIGURE', 'FINALLY', 'FINANCE', 'FINANCIAL', 'FINDING', 'FINGER', 'FINISH', 'FISHING', 'FITNESS', 'FLAVOR', 'FLIGHT', 'FLOWER', 'FOLLOW', 'FOLLOWING', 'FOOTBALL', 'FOREIGN', 'FOREST', 'FOREVER', 'FORGET', 'FORMAL', 'FORMATION', 'FORMER', 'FORMULA', 'FORTUNE', 'FORWARD', 'FOUNDATION', 'FOUNDER', 'FOURTH', 'FRAMEWORK', 'FREEDOM', 'FREEZE', 'FRENCH', 'FREQUENCY', 'FREQUENT', 'FREQUENTLY', 'FRIEND', 'FRIENDLY', 'FRIENDSHIP', 'FRUSTRATION', 'FUNCTION', 'FUNDAMENTAL', 'FUNDING', 'FUNERAL', 'FURNITURE', 'FURTHERMORE', 'FUTURE', 'GALAXY', 'GALLERY', 'GARAGE', 'GARDEN', 'GARLIC', 'GATHER', 'GENDER', 'GENERAL', 'GENERALLY', 'GENERATE', 'GENERATION', 'GENETIC', 'GENTLEMAN', 'GENTLY', 'GERMAN', 'GESTURE', 'GIFTED', 'GIRLFRIEND', 'GLANCE', 'GLOBAL', 'GOLDEN', 'GOVERNMENT', 'GOVERNOR', 'GRADUALLY', 'GRADUATE', 'GRANDFATHER', 'GRANDMOTHER', 'GREATEST', 'GROCERY', 'GROUND', 'GROWING', 'GROWTH', 'GUARANTEE', 'GUIDELINE', 'GUILTY', 'HABITAT', 'HANDFUL', 'HANDLE', 'HAPPEN', 'HARDLY', 'HEADLINE', 'HEADQUARTERS', 'HEALTH', 'HEALTHY', 'HEARING', 'HEAVEN', 'HEAVILY', 'HEIGHT', 'HELICOPTER', 'HELPFUL', 'HERITAGE', 'HERSELF', 'HIGHLIGHT', 'HIGHLY', 'HIGHWAY', 'HIMSELF', 'HISTORIAN', 'HISTORIC', 'HISTORICAL', 'HISTORY', 'HOLIDAY', 'HOMELESS', 'HONEST', 'HORIZON', 'HORROR', 'HOSPITAL', 'HOUSEHOLD', 'HOUSING', 'HOWEVER', 'HUNDRED', 'HUNGRY', 'HUNTER', 'HUNTING', 'HUSBAND', 'HYPOTHESIS', 'IDENTIFICATION', 'IDENTIFY', 'IDENTITY', 'IGNORE', 'ILLEGAL', 'ILLNESS', 'ILLUSTRATE', 'IMAGINATION', 'IMAGINE', 'IMMEDIATE', 'IMMEDIATELY', 'IMMIGRANT', 'IMMIGRATION', 'IMPACT', 'IMPLEMENT', 'IMPLICATION', 'IMPORTANCE', 'IMPORTANT', 'IMPOSE', 'IMPOSSIBLE', 'IMPRESS', 'IMPRESSION', 'IMPRESSIVE', 'IMPROVE', 'IMPROVEMENT', 'INCENTIVE', 'INCIDENT', 'INCLUDE', 'INCLUDING', 'INCOME', 'INCORPORATE', 'INCREASE', 'INCREASED', 'INCREASING', 'INCREASINGLY', 'INCREDIBLE', 'INDEED', 'INDEPENDENCE', 'INDEPENDENT', 'INDIAN', 'INDICATE', 'INDICATION', 'INDIVIDUAL', 'INDUSTRIAL', 'INDUSTRY', 'INFANT', 'INFECTION', 'INFLATION', 'INFLUENCE', 'INFORM', 'INFORMATION', 'INGREDIENT', 'INITIAL', 'INITIALLY', 'INITIATIVE', 'INJURY', 'INNOCENT', 'INQUIRY', 'INSIDE', 'INSIGHT', 'INSIST', 'INSPIRE', 'INSTALL', 'INSTANCE', 'INSTEAD', 'INSTITUTION', 'INSTITUTIONAL', 'INSTRUCTION', 'INSTRUCTOR', 'INSTRUMENT', 'INSURANCE', 'INTELLECTUAL', 'INTELLIGENCE', 'INTEND', 'INTENSE', 'INTENSITY', 'INTENTION', 'INTERACTION', 'INTEREST', 'INTERESTED', 'INTERESTING', 'INTERNAL', 'INTERNATIONAL', 'INTERNET', 'INTERPRET', 'INTERPRETATION', 'INTERVENTION', 'INTERVIEW', 'INTRODUCE', 'INTRODUCTION', 'INVASION', 'INVEST', 'INVESTIGATE', 'INVESTIGATION', 'INVESTIGATOR', 'INVESTMENT', 'INVESTOR', 'INVITE', 'INVOLVE', 'INVOLVED', 'INVOLVEMENT', 'ISLAMIC', 'ISLAND', 'ISRAELI', 'ITALIAN', 'ITSELF', 'JACKET', 'JAPANESE', 'JEWISH', 'JOURNAL', 'JOURNALIST', 'JOURNEY', 'JUDGMENT', 'JUNIOR', 'JUSTICE', 'JUSTIFY', 'KILLER', 'KILLING', 'KITCHEN', 'KNOWLEDGE', 'LABORATORY', 'LANDSCAPE', 'LANGUAGE', 'LARGELY', 'LATTER', 'LAUNCH', 'LAWSUIT', 'LAWYER', 'LEADER', 'LEADERSHIP', 'LEADING', 'LEAGUE', 'LEARNING', 'LEATHER', 'LEGACY', 'LEGEND', 'LEGISLATION', 'LEGITIMATE', 'LENGTH', 'LESSON', 'LETTER', 'LIBERAL', 'LIBRARY', 'LICENSE', 'LIFESTYLE', 'LIFETIME', 'LIKELY', 'LIMITATION', 'LIMITED', 'LISTEN', 'LITERALLY', 'LITERARY', 'LITERATURE', 'LITTLE', 'LIVING', 'LOCATE', 'LOCATION', 'LONG-TERM', 'LOVELY', 'MACHINE', 'MAGAZINE', 'MAINLY', 'MAINTAIN', 'MAINTENANCE', 'MAJORITY', 'MAKEUP', 'MANAGE', 'MANAGEMENT', 'MANAGER', 'MANNER', 'MANUFACTURER', 'MANUFACTURING', 'MARGIN', 'MARKET', 'MARKETING', 'MARRIAGE', 'MARRIED', 'MASSIVE', 'MASTER', 'MATERIAL', 'MATTER', 'MEANING', 'MEANWHILE', 'MEASURE', 'MEASUREMENT', 'MECHANISM', 'MEDICAL', 'MEDICATION', 'MEDICINE', 'MEDIUM', 'MEETING', 'MEMBER', 'MEMBERSHIP', 'MEMORY', 'MENTAL', 'MENTION', 'MERELY', 'MESSAGE', 'METHOD', 'MEXICAN', 'MIDDLE', 'MILITARY', 'MILLION', 'MINISTER', 'MINORITY', 'MINUTE', 'MIRACLE', 'MIRROR', 'MISSILE', 'MISSION', 'MISTAKE', 'MIXTURE', 'MM-HMM', 'MODERATE', 'MODERN', 'MODEST', 'MOMENT', 'MONITOR', 'MOREOVER', 'MORNING', 'MORTGAGE', 'MOSTLY', 'MOTHER', 'MOTION', 'MOTIVATION', 'MOUNTAIN', 'MOVEMENT', 'MULTIPLE', 'MURDER', 'MUSCLE', 'MUSEUM', 'MUSICAL', 'MUSICIAN', 'MUSLIM', 'MUTUAL', 'MYSELF', 'MYSTERY', 'NARRATIVE', 'NARROW', 'NATION', 'NATIONAL', 'NATIVE', 'NATURAL', 'NATURALLY', 'NATURE', 'NEARBY', 'NEARLY', 'NECESSARILY', 'NECESSARY', 'NEGATIVE', 'NEGOTIATE', 'NEGOTIATION', 'NEIGHBOR', 'NEIGHBORHOOD', 'NEITHER', 'NERVOUS', 'NETWORK', 'NEVERTHELESS', 'NEWSPAPER', 'NOBODY', 'NOMINATION', 'NONETHELESS', 'NORMAL', 'NORMALLY', 'NORTHERN', 'NOTHING', 'NOTICE', 'NOTION', 'NOWHERE', 'NUCLEAR', 'NUMBER', 'NUMEROUS', 'OBJECT', 'OBJECTIVE', 'OBLIGATION', 'OBSERVATION', 'OBSERVE', 'OBSERVER', 'OBTAIN', 'OBVIOUS', 'OBVIOUSLY', 'OCCASION', 'OCCASIONALLY', 'OCCUPATION', 'OCCUPY', 'OFFENSE', 'OFFENSIVE', 'OFFICE', 'OFFICER', 'OFFICIAL', 'OLYMPIC', 'ONGOING', 'ONLINE', 'OPENING', 'OPERATE', 'OPERATING', 'OPERATION', 'OPERATOR', 'OPINION', 'OPPONENT', 'OPPORTUNITY', 'OPPOSE', 'OPPOSITE', 'OPPOSITION', 'OPTION', 'ORANGE', 'ORDINARY', 'ORGANIC', 'ORGANIZATION', 'ORGANIZE', 'ORIENTATION', 'ORIGIN', 'ORIGINAL', 'ORIGINALLY', 'OTHERS', 'OTHERWISE', 'OURSELVES', 'OUTCOME', 'OUTSIDE', 'OVERALL', 'OVERCOME', 'OVERLOOK', 'PACKAGE', 'PAINFUL', 'PAINTER', 'PAINTING', 'PALESTINIAN', 'PARENT', 'PARKING', 'PARTICIPANT', 'PARTICIPATE', 'PARTICIPATION', 'PARTICULAR', 'PARTICULARLY', 'PARTLY', 'PARTNER', 'PARTNERSHIP', 'PASSAGE', 'PASSENGER', 'PASSION', 'PATIENT', 'PATTERN', 'PAYMENT', 'PENALTY', 'PEOPLE', 'PEPPER', 'PERCEIVE', 'PERCENTAGE', 'PERCEPTION', 'PERFECT', 'PERFECTLY', 'PERFORM', 'PERFORMANCE', 'PERHAPS', 'PERIOD', 'PERMANENT', 'PERMISSION', 'PERMIT', 'PERSON', 'PERSONAL', 'PERSONALITY', 'PERSONALLY', 'PERSONNEL', 'PERSPECTIVE', 'PERSUADE', 'PHENOMENON', 'PHILOSOPHY', 'PHOTOGRAPH', 'PHOTOGRAPHER', 'PHRASE', 'PHYSICAL', 'PHYSICALLY', 'PHYSICIAN', 'PICTURE', 'PLANET', 'PLANNING', 'PLASTIC', 'PLATFORM', 'PLAYER', 'PLEASE', 'PLEASURE', 'PLENTY', 'POCKET', 'POETRY', 'POLICE', 'POLICY', 'POLITICAL', 'POLITICALLY', 'POLITICIAN', 'POLITICS', 'POLLUTION', 'POPULAR', 'POPULATION', 'PORTION', 'PORTRAIT', 'PORTRAY', 'POSITION', 'POSITIVE', 'POSSESS', 'POSSIBILITY', 'POSSIBLE', 'POSSIBLY', 'POTATO', 'POTENTIAL', 'POTENTIALLY', 'POVERTY', 'POWDER', 'POWERFUL', 'PRACTICAL', 'PRACTICE', 'PRAYER', 'PRECISELY', 'PREDICT', 'PREFER', 'PREFERENCE', 'PREGNANCY', 'PREGNANT', 'PREPARATION', 'PREPARE', 'PRESCRIPTION', 'PRESENCE', 'PRESENT', 'PRESENTATION', 'PRESERVE', 'PRESIDENT', 'PRESIDENTIAL', 'PRESSURE', 'PRETEND', 'PRETTY', 'PREVENT', 'PREVIOUS', 'PREVIOUSLY', 'PRIEST', 'PRIMARILY', 'PRIMARY', 'PRINCIPAL', 'PRINCIPLE', 'PRIORITY', 'PRISON', 'PRISONER', 'PRIVACY', 'PRIVATE', 'PROBABLY', 'PROBLEM', 'PROCEDURE', 'PROCEED', 'PROCESS', 'PRODUCE', 'PRODUCER', 'PRODUCT', 'PRODUCTION', 'PROFESSION', 'PROFESSIONAL', 'PROFESSOR', 'PROFILE', 'PROFIT', 'PROGRAM', 'PROGRESS', 'PROJECT', 'PROMINENT', 'PROMISE', 'PROMOTE', 'PROMPT', 'PROPER', 'PROPERLY', 'PROPERTY', 'PROPORTION', 'PROPOSAL', 'PROPOSE', 'PROPOSED', 'PROSECUTOR', 'PROSPECT', 'PROTECT', 'PROTECTION', 'PROTEIN', 'PROTEST', 'PROVIDE', 'PROVIDER', 'PROVINCE', 'PROVISION', 'PSYCHOLOGICAL', 'PSYCHOLOGIST', 'PSYCHOLOGY', 'PUBLIC', 'PUBLICATION', 'PUBLICLY', 'PUBLISH', 'PUBLISHER', 'PUNISHMENT', 'PURCHASE', 'PURPOSE', 'PURSUE', 'QUALIFY', 'QUALITY', 'QUARTER', 'QUARTERBACK', 'QUESTION', 'QUICKLY', 'QUIETLY', 'RACIAL', 'RADICAL', 'RAPIDLY', 'RARELY', 'RATHER', 'RATING', 'REACTION', 'READER', 'READING', 'REALITY', 'REALIZE', 'REALLY', 'REASON', 'REASONABLE', 'RECALL', 'RECEIVE', 'RECENT', 'RECENTLY', 'RECIPE', 'RECOGNITION', 'RECOGNIZE', 'RECOMMEND', 'RECOMMENDATION', 'RECORD', 'RECORDING', 'RECOVER', 'RECOVERY', 'RECRUIT', 'REDUCE', 'REDUCTION', 'REFERENCE', 'REFLECT', 'REFLECTION', 'REFORM', 'REFUGEE', 'REFUSE', 'REGARD', 'REGARDING', 'REGARDLESS', 'REGIME', 'REGION', 'REGIONAL', 'REGISTER', 'REGULAR', 'REGULARLY', 'REGULATE', 'REGULATION', 'REINFORCE', 'REJECT', 'RELATE', 'RELATION', 'RELATIONSHIP', 'RELATIVE', 'RELATIVELY', 'RELEASE', 'RELEVANT', 'RELIEF', 'RELIGION', 'RELIGIOUS', 'REMAIN', 'REMAINING', 'REMARKABLE', 'REMEMBER', 'REMIND', 'REMOTE', 'REMOVE', 'REPEAT', 'REPEATEDLY', 'REPLACE', 'REPORT', 'REPORTER', 'REPRESENT', 'REPRESENTATION', 'REPRESENTATIVE', 'REPUBLICAN', 'REPUTATION', 'REQUEST', 'REQUIRE', 'REQUIREMENT', 'RESEARCH', 'RESEARCHER', 'RESEMBLE', 'RESERVATION', 'RESIDENT', 'RESIST', 'RESISTANCE', 'RESOLUTION', 'RESOLVE', 'RESORT', 'RESOURCE', 'RESPECT', 'RESPOND', 'RESPONDENT', 'RESPONSE', 'RESPONSIBILITY', 'RESPONSIBLE', 'RESTAURANT', 'RESTORE', 'RESTRICTION', 'RESULT', 'RETAIN', 'RETIRE', 'RETIREMENT', 'RETURN', 'REVEAL', 'REVENUE', 'REVIEW', 'REVOLUTION', 'RHYTHM', 'ROMANTIC', 'ROUGHLY', 'ROUTINE', 'RUNNING', 'RUSSIAN', 'SACRED', 'SAFETY', 'SALARY', 'SAMPLE', 'SANCTION', 'SATELLITE', 'SATISFACTION', 'SATISFY', 'SAVING', 'SCANDAL', 'SCARED', 'SCENARIO', 'SCHEDULE', 'SCHEME', 'SCHOLAR', 'SCHOLARSHIP', 'SCHOOL', 'SCIENCE', 'SCIENTIFIC', 'SCIENTIST', 'SCREAM', 'SCREEN', 'SCRIPT', 'SEARCH', 'SEASON', 'SECOND', 'SECRET', 'SECRETARY', 'SECTION', 'SECTOR', 'SECURE', 'SECURITY', 'SEGMENT', 'SELECT', 'SELECTION', 'SENATE', 'SENATOR', 'SENIOR', 'SENSITIVE', 'SENTENCE', 'SEPARATE', 'SEQUENCE', 'SERIES', 'SERIOUS', 'SERIOUSLY', 'SERVICE', 'SESSION', 'SETTING', 'SETTLE', 'SETTLEMENT', 'SEVERAL', 'SEVERE', 'SEXUAL', 'SHADOW', 'SHELTER', 'SHOOTING', 'SHOPPING', 'SHORTLY', 'SHOULD', 'SHOULDER', 'SHOWER', 'SIGNAL', 'SIGNIFICANCE', 'SIGNIFICANT', 'SIGNIFICANTLY', 'SILENCE', 'SILENT', 'SILVER', 'SIMILAR', 'SIMILARLY', 'SIMPLE', 'SIMPLY', 'SINGER', 'SINGLE', 'SISTER', 'SITUATION', 'SLIGHT', 'SLIGHTLY', 'SLOWLY', 'SMOOTH', 'SO-CALLED', 'SOCCER', 'SOCIAL', 'SOCIETY', 'SOFTWARE', 'SOLDIER', 'SOLUTION', 'SOMEBODY', 'SOMEHOW', 'SOMEONE', 'SOMETHING', 'SOMETIMES', 'SOMEWHAT', 'SOMEWHERE', 'SOPHISTICATED', 'SOURCE', 'SOUTHERN', 'SOVIET', 'SPANISH', 'SPEAKER', 'SPECIAL', 'SPECIALIST', 'SPECIES', 'SPECIFIC', 'SPECIFICALLY', 'SPEECH', 'SPENDING', 'SPIRIT', 'SPIRITUAL', 'SPOKESMAN', 'SPREAD', 'SPRING', 'SQUARE', 'SQUEEZE', 'STABILITY', 'STABLE', 'STANDARD', 'STANDING', 'STATEMENT', 'STATION', 'STATISTICS', 'STATUS', 'STEADY', 'STOMACH', 'STORAGE', 'STRAIGHT', 'STRANGE', 'STRANGER', 'STRATEGIC', 'STRATEGY', 'STREAM', 'STREET', 'STRENGTH', 'STRENGTHEN', 'STRESS', 'STRETCH', 'STRIKE', 'STRING', 'STROKE', 'STRONG', 'STRONGLY', 'STRUCTURE', 'STRUGGLE', 'STUDENT', 'STUDIO', 'STUPID', 'SUBJECT', 'SUBMIT', 'SUBSEQUENT', 'SUBSTANCE', 'SUBSTANTIAL', 'SUCCEED', 'SUCCESS', 'SUCCESSFUL', 'SUCCESSFULLY', 'SUDDEN', 'SUDDENLY', 'SUFFER', 'SUFFICIENT', 'SUGGEST', 'SUGGESTION', 'SUICIDE', 'SUMMER', 'SUMMIT', 'SUPPLY', 'SUPPORT', 'SUPPORTER', 'SUPPOSE', 'SUPPOSED', 'SUPREME', 'SURELY', 'SURFACE', 'SURGERY', 'SURPRISE', 'SURPRISED', 'SURPRISING', 'SURPRISINGLY', 'SURROUND', 'SURVEY', 'SURVIVAL', 'SURVIVE', 'SURVIVOR', 'SUSPECT', 'SUSTAIN', 'SWITCH', 'SYMBOL', 'SYMPTOM', 'SYSTEM', 'TABLESPOON', 'TACTIC', 'TALENT', 'TARGET', 'TAXPAYER', 'TEACHER', 'TEACHING', 'TEASPOON', 'TECHNICAL', 'TECHNIQUE', 'TECHNOLOGY', 'TEENAGER', 'TELEPHONE', 'TELESCOPE', 'TELEVISION', 'TEMPERATURE', 'TEMPORARY', 'TENDENCY', 'TENNIS', 'TENSION', 'TERRIBLE', 'TERRITORY', 'TERROR', 'TERRORISM', 'TERRORIST', 'TESTIFY', 'TESTIMONY', 'TESTING', 'THANKS', 'THEATER', 'THEMSELVES', 'THEORY', 'THERAPY', 'THEREFORE', 'THINKING', 'THIRTY', 'THOUGH', 'THOUGHT', 'THOUSAND', 'THREAT', 'THREATEN', 'THROAT', 'THROUGH', 'THROUGHOUT', 'TICKET', 'TISSUE', 'TOBACCO', 'TOGETHER', 'TOMATO', 'TOMORROW', 'TONGUE', 'TONIGHT', 'TOTALLY', 'TOURIST', 'TOURNAMENT', 'TOWARD', 'TOWARDS', 'TRADITION', 'TRADITIONAL', 'TRAFFIC', 'TRAGEDY', 'TRAINING', 'TRANSFER', 'TRANSFORM', 'TRANSFORMATION', 'TRANSITION', 'TRANSLATE', 'TRANSPORTATION', 'TRAVEL', 'TREATMENT', 'TREATY', 'TREMENDOUS', 'TROUBLE', 'TUNNEL', 'TWELVE', 'TWENTY', 'TYPICAL', 'TYPICALLY', 'ULTIMATE', 'ULTIMATELY', 'UNABLE', 'UNDERGO', 'UNDERSTAND', 'UNDERSTANDING', 'UNFORTUNATELY', 'UNIFORM', 'UNIQUE', 'UNITED', 'UNIVERSAL', 'UNIVERSE', 'UNIVERSITY', 'UNKNOWN', 'UNLESS', 'UNLIKE', 'UNLIKELY', 'UNUSUAL', 'USEFUL', 'USUALLY', 'UTILITY', 'VACATION', 'VALLEY', 'VALUABLE', 'VARIABLE', 'VARIATION', 'VARIETY', 'VARIOUS', 'VEGETABLE', 'VEHICLE', 'VENTURE', 'VERSION', 'VERSUS', 'VESSEL', 'VETERAN', 'VICTIM', 'VICTORY', 'VIEWER', 'VILLAGE', 'VIOLATE', 'VIOLATION', 'VIOLENCE', 'VIOLENT', 'VIRTUALLY', 'VIRTUE', 'VISIBLE', 'VISION', 'VISITOR', 'VISUAL', 'VOLUME', 'VOLUNTEER', 'VULNERABLE', 'WANDER', 'WARNING', 'WEALTH', 'WEALTHY', 'WEAPON', 'WEATHER', 'WEDDING', 'WEEKEND', 'WEEKLY', 'WEIGHT', 'WELCOME', 'WELFARE', 'WESTERN', 'WHATEVER', 'WHENEVER', 'WHEREAS', 'WHETHER', 'WHISPER', 'WIDELY', 'WIDESPREAD', 'WILLING', 'WINDOW', 'WINNER', 'WINTER', 'WISDOM', 'WITHDRAW', 'WITHIN', 'WITHOUT', 'WITNESS', 'WONDER', 'WONDERFUL', 'WOODEN', 'WORKER', 'WORKING', 'WORKSHOP', 'WORRIED', 'WRITER', 'WRITING', 'YELLOW', 'YESTERDAY', 'YOURSELF']

let gameOver = false;
let word = words[Math.floor(Math.random() * words.length)]
width = word.length;
let root = document.querySelector(':root');
root.style.setProperty('--boardWidth', (width+1)*65+"px");
root.style.setProperty('--boardHeight', (height)*65+"px");
root.style.setProperty('--flipDuration', animationDuration+"ms");

function setCharAt(str,index,chr) {
    if(index > str.length-1) return str;
    return str.substring(0,index) + chr + str.substring(index+1);
}

window.onload = function(){
    play.onclick = reset;
}

function reset(){
    while (board.lastChild) {
        board.removeChild(board.lastChild);
    }
    while (letters.lastChild){
        letters.removeChild(letters.lastChild);
    }
    height = 5; // Number of Guesses
    width = 8; // Length of Word

    if (difficulty.value == "ultra-hard"){
        height = 3;
    }

    row = 0; // Current Guess Attempt
    col = 0; // Current Letter

    gameOver = false;
    word = words[Math.floor(Math.random() * words.length)]

    width = word.length;

    root = document.querySelector(':root');
    root.style.setProperty('--boardWidth', (width+1)*65+"px");
    root.style.setProperty('--boardHeight', (height)*65+"px");
    root.style.setProperty('--flipDuration', animationDuration+"ms");

    document.getElementById("play").setAttribute("disabled", "true")
    document.getElementById("difficulty").setAttribute("disabled", "true")
    document.getElementById("answer").innerText = "";

    initialise();
}

function initialise(){
    document.removeEventListener("keydown",keyPress);
    // Shuffle Word
    let reShuffle = true;
    while (reShuffle){
    shuffledWord = shuffleWord(word)
    let similarity = getSimilarity(word, shuffledWord)
    if (similarity < 0.2){
        reShuffle = false
        }
    }

    if (difficulty.value == "ultra-hard" || difficulty.value == "hard"){
        for (let i = 0; i < Math.floor(shuffledWord.length/2); i++){
            shuffledWord = setCharAt(shuffledWord, i, "-")
        }
    }

    letterDisplay = document.getElementById("letters");
    for (letter in shuffledWord){
        let letteritem = document.createElement("span");
        letteritem.innerText = shuffledWord[letter];
        letteritem.classList.add("displayLetters")
        letterDisplay.appendChild(letteritem);

    }


    // Create Board
    for (let r = 0; r < height; r++){
        for (let c = 0; c < width; c++){
            let tile = document.createElement("span");
            tile.id = r.toString() + "-" + c.toString();
            tile.classList.add("tile");
            tile.innerText = "";
            document.getElementById("board").appendChild(tile)
        }
    }

    // Listen for keypress
    document.addEventListener("keyup", keyPress);
}

function shuffleWord(string){
    let shuffledString = "";
    let remainingLetters = string;

    while (remainingLetters.length > 0){
        let letterIndex = Math.floor(Math.random() * remainingLetters.length);
        shuffledString = shuffledString + remainingLetters[letterIndex];
        remainingLetters = removeByIndex(remainingLetters, letterIndex)
        }
    return shuffledString;
}

function keyPress(e){
    if (gameOver) return;

    if ("KeyA" <= e.code && e.code <= "KeyZ"){
        if (col < width){
            let currentTile = document.getElementById(row.toString() + "-" + col.toString());
            if (currentTile.innerText == ""){
                currentTile.innerText = e.code[3];
                col++;
            }

        }
    }
    else if (e.code == "Backspace"){
        if (0 < col && col <= width){
            col--;
            let currentTile = document.getElementById(row.toString() + "-" + col.toString());
            currentTile.innerText = "";

        }
    }
    else if (e.code == "Enter"){
        if (col == width){
        update();
        row += 1;
        col = 0;
        }
        
    }

    if (!gameOver && row == height) {
        gameOver = true;
        document.getElementById("answer").innerText = word;
        document.getElementById("play").removeAttribute("disabled")
        document.getElementById("difficulty").removeAttribute("disabled")
    }
}

function removeByIndex(str,index) {
    return str.slice(0,index) + str.slice(index+1);
}

function getSimilarity(str1, str2){
    

var shortest = str2.length >= str1.length?str1:str2
var longest = str2.length < str1.length?str1:str2

var matches= 0

shortest
.split("")
//Just check if index of shortest
//Matches index of longest, and if so (&& means do next
//Expression) add the total number of matches by one
.forEach (
(x,k)=>
((x==longest[k]) && (matches++) )
)

//Final result, divide matches by total length
return matches / shortest.length;

}

function update(){
    let correct = 0;
    for (let c = 0; c < width; c++){
        let currentTile = document.getElementById(row.toString() + "-" + c.toString());
        let letter = currentTile.innerText;
        

        setTimeout(() => {if (word[c] == letter) {
            currentTile.classList.add("correct");
            correct ++;
        }
        else if (word.includes(letter)){
            currentTile.classList.add("present");
        }
        else{
            currentTile.classList.add("absent");
        }

        if (correct == width){
            gameOver = true;
            document.getElementById("play").removeAttribute("disabled")
            document.getElementById("difficulty").removeAttribute("disabled")
        }}, ((c + 1) * animationDuration) / 2);

        currentTile.classList.add("animated");
        currentTile.style.animationDelay = `${(c * animationDuration) / 2}ms`;
        
    }
}